'''
Problem 1 -- Multiples of 3 & 5

If we list all the natural numbers below 10 that are 
multiples of 3 or 5, we get 3, 5, 6 and 9. 
The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.
'''

# result = 0

# for i in range(1,1000):
#     if i % 15 == 0 or i % 5 == 0 or i % 3 == 0:
#         result += i

# print(result)




'''
Problem 2 -- Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose 
values do not exceed four million, find the sum of the 
even-valued terms.
'''


# result = 0

# num1 = 1
# num2 = 1

# while num2 <= 4000000:
#     next_num = num1 + num2
#     if next_num % 2 == 0:
#         result += next_num
#     num1 = num2
#     num2 = next_num

# print(result)



'''
Problem 3 -- Largest Prime Factor

The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?
'''

# from math import sqrt
# num = 600851475143
# prime_factors = []

# for i in range(3, int(sqrt(num)) + 1, 2):
#     if num % i == 0 and all(i%j!=0 for j in range(2, int(sqrt(i) + 1))):
#         prime_factors.append(i)
    
# prime_factors.sort(reverse=True)
# print(prime_factors)




'''
Problem 4 -- Lagest Palindrome Product
A palindromic number reads the same both ways. 
The largest palindrome made from the product of two 
2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.
'''

# from math import floor, ceil
# def isPalindrome(num):
#     string_num = str(num)
#     even = (len(string_num) % 2 + 1) % 2
#     if string_num[:floor(len(string_num)/2)] == string_num[:floor(len(string_num)/2) - even:-1]:
#         return True
#     return False

# max_num = 0
# for i in range(1000, 100, -1):
#     for j in range(i, 100 , -1):
#         if i * j < max_num:
#             break

#         if isPalindrome(i*j):
#             max_num = i*j
#             num1 = i
#             num2 = j

# print(max_num, num1, num2)





'''
Problem 5 -- Smallest Multiple
2520 is the smallest number that can be divided by each 
of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly 
divisible by all of the numbers from 1 to 20?
'''
# from math import sqrt
# from functools import reduce
# # num = 1
# # for k in range(1,21):
# #     num *= k
# num = 3628800


# primes = [i for i in range(2, 21) if all(i%j!=0 for j in range(2, int(sqrt(i)) + 1))]

# def gcd(a,b):
#     while b:
#         a, b = b, a%b
#     return a

# def lcm(a,b):
#     return (a*b)/gcd(a,b)

# print(reduce(lcm, [i for i in range(1,21)]))




'''
Sum square difference

Problem 6
The sum of the squares of the first ten natural numbers is,
385

The square of the sum of the first ten natural numbers is,
3025

Hence the difference between the sum of the squares of the 
first ten natural numbers and the square of the sum is .
2640

Find the difference between the sum of the squares of the 
first one hundred natural numbers and the square of the sum.
'''

# nums = [i for i in range(1,101)]

# sum_of_squares = 0
# square_of_sum = 0

# for num in nums:
#     sum_of_squares += num ** 2
#     square_of_sum += num

# print(square_of_sum ** 2 - sum_of_squares)






'''
Problem 7
10001st prime

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, 
we can see that the 6th prime is 13.

What is the 10001st prime number?
'''

# from math import sqrt

# primes = []

# i = 2
# while len(primes) < 10001:
#     if all(i%j!=0 for j in range(2, int(sqrt(i)) + 1)):
#         primes.append(i)
#     i += 1

# print(primes[-1])



'''
Problem 8
Largest product in a series

The four adjacent digits in the 1000-digit number that have the greatest product 
are 9 × 9 × 8 × 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number 
that have the greatest product. What is the value of this product?

'''

# num = '73167176531330624919225119674426574742355349194934\
# 96983520312774506326239578318016984801869478851843\
# 85861560789112949495459501737958331952853208805511\
# 12540698747158523863050715693290963295227443043557\
# 66896648950445244523161731856403098711121722383113\
# 62229893423380308135336276614282806444486645238749\
# 30358907296290491560440772390713810515859307960866\
# 70172427121883998797908792274921901699720888093776\
# 65727333001053367881220235421809751254540594752243\
# 52584907711670556013604839586446706324415722155397\
# 53697817977846174064955149290862569321978468622482\
# 83972241375657056057490261407972968652414535100474\
# 82166370484403199890008895243450658541227588666881\
# 16427171479924442928230863465674813919123162824586\
# 17866458359124566529476545682848912883142607690042\
# 24219022671055626321111109370544217506941658960408\
# 07198403850962455444362981230987879927244284909188\
# 84580156166097919133875499200524063689912560717606\
# 05886116467109405077541002256983155200055935729725\
# 71636269561882670428252483600823257530420752963450'


# adjacent = 13
# max_product = 1

# for i in range(len(num) - adjacent):
#     product = int(num[i])
#     for j in range(1, adjacent):
#         product *= int(num[i+j])
#     if product > max_product:
#         max_product = product
    
# print(max_product)



'''
Problem 9
Special Pythagorean Triplet

A Pythagorean triplet is a set of three natural numbers, a < b < c, 
for which,

a**2 + b**2 = c**2
For example, 3**2 + 4**2 = 9 + 16 = 25 = 5**2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.
'''


# pyth_list = []
# for n in range(1, 90):
#     for m in range(n, 100):
#         a = m**2 - n**2
#         b = 2*m*n
#         c = m**2 + n**2
#         pyth_list.append([(a,b,c), a+b+c])
        
# for item in pyth_list:
#     if item[1] == 1000:
#         print(item)
#         print(item[0][0] * item[0][1] * item[0][2])


'''
Problem 10
Summation of Primes

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million
'''
from math import sqrt

prime_sum = sum([i for i in range(2, 2000000) if all(i%j!=0 for j in range(2, int(sqrt(i)) + 1))])
print(prime_sum)